# Generated by Django 3.2.4 on 2021-07-15 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'verbose_name': '답변하기', 'verbose_name_plural': '답변하기'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': '질문하기', 'verbose_name_plural': '질문하기'},
        ),
        migrations.AlterModelTable(
            name='answer',
            table='답변하기',
        ),
        migrations.AlterModelTable(
            name='question',
            table='질문하기',
        ),
    ]
