# Generated by Django 3.2.4 on 2021-07-13 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tip',
            options={'ordering': ('title',), 'verbose_name': '법률팁', 'verbose_name_plural': '법률팁'},
        ),
    ]
