# Generated by Django 3.2.4 on 2021-07-13 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0004_alter_tip_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tip',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='upload_loaction', verbose_name='이미지'),
        ),
    ]
