# Generated by Django 3.2.4 on 2021-07-14 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0007_alter_tip_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tip',
            name='video_key',
        ),
        migrations.AddField(
            model_name='tip',
            name='url',
            field=models.URLField(null=True, verbose_name='URL'),
        ),
    ]
