# Generated by Django 3.2.4 on 2021-07-17 06:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lawyer_comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='후기내용')),
                ('time_point', models.IntegerField()),
                ('kindness_point', models.IntegerField()),
                ('solution_point', models.IntegerField()),
                ('created_date', models.DateTimeField(blank=True, null=True, verbose_name='후기작성일')),
                ('name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='이름')),
            ],
            options={
                'verbose_name': '변호사찾기 댓글',
                'verbose_name_plural': '변호사찾기 댓글',
                'db_table': '변호사찾기 댓글',
            },
        ),
        migrations.CreateModel(
            name='Lawyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50, null=True, verbose_name='이메일')),
                ('title', models.CharField(max_length=40, verbose_name='제목')),
                ('content', models.TextField(verbose_name='내용')),
                ('company_address', models.CharField(max_length=128, verbose_name='회사주소')),
                ('company_phone_number', models.IntegerField(verbose_name='회사전화번호')),
                ('career', models.CharField(max_length=128, verbose_name='경력')),
                ('qualification', models.TextField(verbose_name='자격')),
                ('education', models.TextField(verbose_name='학력')),
                ('activity', models.TextField(verbose_name='활동사항')),
                ('img', models.ImageField(blank=True, null=True, upload_to='lawyer_img', verbose_name='변호사 이미지')),
                ('name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='이름')),
            ],
            options={
                'verbose_name': '변호사찾기',
                'verbose_name_plural': '변호사찾기',
                'db_table': '변호사찾기',
            },
        ),
    ]
