# Generated by Django 3.2.4 on 2021-07-18 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawyer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawyer',
            name='company_name',
            field=models.CharField(max_length=20, null=True, verbose_name='회사이름'),
        ),
        migrations.AlterField(
            model_name='lawyer',
            name='career',
            field=models.TextField(blank=True, null=True, verbose_name='경력내용'),
        ),
    ]
