# Generated by Django 3.2.4 on 2021-07-09 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('free', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='hits',
            field=models.PositiveIntegerField(default=0, verbose_name='조회수'),
        ),
    ]
